project:
  type: website

website:
  title: "ISSS608-Coursework Website"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-onExercise 1"
        href: "HE01.html"
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: "IE01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true

editor: visual

